name: Build iOS Dylib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # 使用完全不排隊的 Linux 伺服器
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Theos
        run: |
          bash -c "$(curl -fsSL https://githubusercontent.com)"
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build Dylib
        run: |
          export THEOS=~/theos
          make
          
      - name: Upload Dylib Artifact
        uses: actions/upload-artifacts@v3
        with:
          name: BABypass-Dylib
          path: .theos/obj/debug/*.dylib






          
