name: Build iOS Dylib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 這次我們只抓核心，因為核心裡已經有足夠編譯普通 Tweak 的 SDK 了！
      - name: Install Theos Directly
        run: |
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          export THEOS=$HOME/theos
          git clone --recursive https://github.com $THEOS

      - name: Build Dylib
        run: |
          export THEOS=$HOME/theos
          make TARGET=iphone:clang:latest:14.0
          
      - name: Upload Dylib Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BABypass-Dylib
          path: .theos/obj/debug/*.dylib
